import type { Memo, Sky } from "@/lib/types";

const ideaMemo: Memo = {
  id: "next-ui-concept",
  category: "アイデア",
  title: "次世代UIコンセプト",
  summary: "音声入力中心のインターフェース設計案。ユーザーの認知負荷を下げるために...",
  createdAtLabel: "14:02",
  pinned: false,
  summaryA: [
    { id: "s1", text: "音声入力を主軸にしたUIで、視覚的ノイズを極限まで削減する設計案" },
    { id: "s2", text: "認知負荷の低減が最優先。ボタン数を3つ以下に抑えるルールを提案" },
    { id: "s3", text: "競合分析でWhisperとNotionの音声機能を参照。差別化ポイントは即時圧縮" },
    { id: "s4", text: "プロトタイプは来週金曜（11/1）までに完成。デザインチームでレビュー予定" },
  ],
  keyFacts: [
    { id: "k1", icon: "calendar", value: "11/1（金）" },
    { id: "k2", icon: "team", value: "デザインチーム" },
    { id: "k3", icon: "reference", value: "Whisper / Notion" },
  ],
  openLoops: ["「ボタン3つ以下」のルールが全画面に適用されるか未確認"],
  recordingDuration: "01:47",
  tags: ["UI", "音声", "設計"],
  expanded:
    "音声中心のUIを試作し、情報階層を最小化する案。ユーザーの操作回数を減らし、学習コストを抑える。次回は検証対象の画面を3つに絞り、視線移動と認知負荷を測定する。",
  transcript: "次世代UIの方向性として、入力を音声中心に寄せたい。",
};

const meetingMemo: Memo = {
  id: "q4-regular-meeting",
  category: "ミーティング",
  title: "Q4 プロジェクト定例",
  summary: "来期の予算配分についての合意事項。開発チームのリソース調整が必要...",
  createdAtLabel: "昨日",
  pinned: true,
  summaryA: [
    { id: "s1", text: "開発とデザインの共通マイルストーンを設定" },
    { id: "s2", text: "バックログ上位10件を2週間で再見積もり" },
    { id: "s3", text: "レビュー会を毎週火曜15時に固定" },
  ],
  keyFacts: [
    { id: "k1", icon: "calendar", value: "毎週火曜 15:00" },
    { id: "k2", icon: "team", value: "開発チーム / PM" },
  ],
  openLoops: ["予算配分の最終承認待ち"],
  recordingDuration: "02:08",
  tags: ["定例", "予算", "進捗"],
  expanded: "予算と体制の調整を中心に進行。優先機能の再定義が必要。",
  transcript: "Q4の定例会議。予算と進捗、採用計画を共有。",
};

const diaryMemo: Memo = {
  id: "autumn-walk-note",
  category: "日記",
  title: "秋の散歩道にて",
  summary: "冷たい風が心地よい。新しい小説のプロットがふと浮かんだ瞬間...",
  createdAtLabel: "10/24",
  pinned: false,
  summaryA: [
    { id: "s1", text: "街路樹の色が物語の導入イメージに一致" },
    { id: "s2", text: "主人公の動機を再構成する必要あり" },
    { id: "s3", text: "週末にプロット第一稿へ反映" },
  ],
  keyFacts: [{ id: "k1", icon: "calendar", value: "週末に執筆" }],
  openLoops: ["登場人物Bの背景設定が未整理"],
  recordingDuration: "00:56",
  tags: ["日記", "創作"],
  expanded: "散歩中に着想したプロット断片をメモ化。",
  transcript: "秋の空気で頭が整理され、物語の冒頭が見えた。",
};

export const mockRecentMemos: Memo[] = [ideaMemo, meetingMemo, diaryMemo];

export const mockInboxMemos: Memo[] = [
  ideaMemo,
  {
    id: "voice-shortcut-patterns",
    category: "アイデア",
    title: "音声ショートカット導線",
    summary: "頻出操作を音声コマンド化。視線移動を減らして操作時間を短縮する。",
    createdAtLabel: "今日",
    pinned: false,
    summaryA: [
      { id: "v1", text: "ホーム遷移と検索を1文で実行する音声導線" },
      { id: "v2", text: "高頻度の3操作を優先して学習させる" },
      { id: "v3", text: "コマンド失敗時は候補提示で復帰" },
    ],
    keyFacts: [
      { id: "k1", icon: "calendar", value: "今週内に検証" },
      { id: "k2", icon: "team", value: "UXチーム" },
    ],
    openLoops: ["誤認識時の再入力導線"],
    recordingDuration: "01:18",
    tags: ["UI", "音声", "操作"],
    expanded: "音声ショートカットの設計方針メモ。",
    transcript: "短いコマンドで画面移動を完了させたい。",
  },
  {
    id: "idea-voice-flow",
    category: "アイデア",
    title: "会話フロー型メモ入力",
    summary: "質問に答えるだけで要約可能なメモ構造へ整形する。",
    createdAtLabel: "2日前",
    pinned: false,
    summaryA: [
      { id: "i1", text: "問い返しテンプレートで情報欠落を補う" },
      { id: "i2", text: "目的・期限・担当を会話内で抽出" },
      { id: "i3", text: "最後にワンタップで確定" },
    ],
    keyFacts: [{ id: "k1", icon: "team", value: "プロダクトチーム" }],
    openLoops: ["会話長が長い場合の切り上げ基準"],
    recordingDuration: "01:29",
    tags: ["UI", "音声", "会話"],
    expanded: "対話型入力のプロトタイプ案。",
    transcript: "質問に答えるだけでメモに落としたい。",
  },
  {
    id: "weekly-planning",
    category: "やること",
    title: "来週の実装タスク整理",
    summary: "認証修正、通知UI、検索改善の3本を優先。",
    createdAtLabel: "今日",
    pinned: true,
    summaryA: [
      { id: "t1", text: "認証バグの再現ケースを先に固定" },
      { id: "t2", text: "通知コンポーネントの差分適用" },
      { id: "t3", text: "検索レスポンスを体感1秒未満へ" },
    ],
    keyFacts: [{ id: "k1", icon: "calendar", value: "来週月曜着手" }],
    openLoops: ["通知UIの文言最終確認"],
    recordingDuration: "00:49",
    tags: ["タスク", "実装", "優先度"],
    expanded: "次スプリント向けTODO。",
    transcript: "優先タスクを3本に絞る。",
  },
  {
    id: "todo-automation",
    category: "やること",
    title: "デプロイ自動化の下準備",
    summary: "CIの失敗率を下げるため、lintとテストを並列化する。",
    createdAtLabel: "昨日",
    pinned: false,
    summaryA: [
      { id: "ta1", text: "lintとunit testをジョブ分割" },
      { id: "ta2", text: "キャッシュキーの見直し" },
      { id: "ta3", text: "失敗通知先をSlackへ統一" },
    ],
    keyFacts: [{ id: "k1", icon: "reference", value: "GitHub Actions" }],
    openLoops: ["E2Eの実行タイミング"],
    recordingDuration: "01:03",
    tags: ["タスク", "実装", "自動化"],
    expanded: "運用負荷を下げるためのCI整備。",
    transcript: "デプロイの失敗を減らすためジョブを分割する。",
  },
  {
    id: "search-accessibility",
    category: "調べもの",
    title: "音声UIのアクセシビリティ調査",
    summary: "スクリーンリーダーと音声操作の干渉パターンを確認。",
    createdAtLabel: "3日前",
    pinned: false,
    summaryA: [
      { id: "r1", text: "ARIA live の読み上げ頻度が課題" },
      { id: "r2", text: "入力中のフォーカス移動を抑制" },
      { id: "r3", text: "主要OSで挙動差がある" },
    ],
    keyFacts: [{ id: "k1", icon: "reference", value: "WCAG 2.2" }],
    openLoops: ["Android TalkBackでの再検証"],
    recordingDuration: "01:12",
    tags: ["調査", "UI", "アクセシビリティ"],
    expanded: "アクセシビリティ観点の調査メモ。",
    transcript: "音声UIとスクリーンリーダーの相性を確認したい。",
  },
  {
    id: "grocery-dinner-plan",
    category: "買い物・ごはん",
    title: "週末の買い物メモ",
    summary: "鶏むね肉、トマト缶、オリーブオイル、バジルを購入。",
    createdAtLabel: "今日",
    pinned: false,
    summaryA: [
      { id: "g1", text: "作り置き用の食材を優先" },
      { id: "g2", text: "日曜の夕食はパスタ" },
      { id: "g3", text: "調味料の在庫確認が必要" },
    ],
    keyFacts: [{ id: "k1", icon: "calendar", value: "日曜 17:00" }],
    openLoops: ["チーズの在庫確認"],
    recordingDuration: "00:31",
    tags: ["買い物", "ごはん", "週末"],
    expanded: "買い物リスト。",
    transcript: "週末の食材を買いに行く。",
  },
  {
    id: "llm-eval-learning",
    category: "学び",
    title: "LLM評価指標の整理",
    summary: "要約品質の評価軸として網羅性・正確性・圧縮率を定義。",
    createdAtLabel: "昨日",
    pinned: false,
    summaryA: [
      { id: "l1", text: "観点ごとにスコアシートを作成" },
      { id: "l2", text: "データセットをカテゴリ別に分離" },
      { id: "l3", text: "誤要約のパターンを定義" },
    ],
    keyFacts: [{ id: "k1", icon: "reference", value: "ROUGE / BERTScore" }],
    openLoops: ["人手評価の基準統一"],
    recordingDuration: "01:42",
    tags: ["学習", "LLM", "要約"],
    expanded: "評価観点の整理メモ。",
    transcript: "要約モデルの評価軸を揃える必要がある。",
  },
  {
    id: "css-glow-study",
    category: "学び",
    title: "薄い境界線とグローの再現",
    summary: "0.5px線と低彩度グローの組み合わせで情報階層を作る。",
    createdAtLabel: "4日前",
    pinned: false,
    summaryA: [
      { id: "cl1", text: "太い影より薄い発光を優先" },
      { id: "cl2", text: "境界線の不透明度は5-8%" },
      { id: "cl3", text: "背景グラデーションは一点集中" },
    ],
    keyFacts: [{ id: "k1", icon: "reference", value: "Tailwind カスタム変数" }],
    openLoops: ["モバイルでの視認性"],
    recordingDuration: "00:58",
    tags: ["学習", "UI", "デザイン"],
    expanded: "UIトーン再現の実験メモ。",
    transcript: "薄い境界線を中心に画面階層を作る。",
  },
  {
    id: "client-followup",
    category: "約束・連絡",
    title: "クライアント確認事項",
    summary: "デモ日程と要件優先度の再確認。",
    createdAtLabel: "今日",
    pinned: true,
    summaryA: [
      { id: "c1", text: "来週金曜のデモ時間を確定" },
      { id: "c2", text: "優先機能3件の合意を取る" },
      { id: "c3", text: "次回会議の参加者を整理" },
    ],
    keyFacts: [{ id: "k1", icon: "calendar", value: "来週金曜 16:00" }],
    openLoops: ["出席者の最終確定"],
    recordingDuration: "00:45",
    tags: ["連絡", "クライアント", "日程"],
    expanded: "対外連絡の確認メモ。",
    transcript: "デモ日程の再確認が必要。",
  },
  {
    id: "saas-cost-tracking",
    category: "お金",
    title: "SaaSコストの見直し",
    summary: "未使用ライセンスを整理し、月額固定費を最適化する。",
    createdAtLabel: "5日前",
    pinned: false,
    summaryA: [
      { id: "m1", text: "利用率20%未満の契約を棚卸し" },
      { id: "m2", text: "年契約の割引条件を確認" },
      { id: "m3", text: "通知閾値を超えたらアラート" },
    ],
    keyFacts: [{ id: "k1", icon: "reference", value: "月額 12%削減目標" }],
    openLoops: ["経理連携の自動化"],
    recordingDuration: "01:05",
    tags: ["予算", "SaaS", "コスト"],
    expanded: "固定費改善の検討メモ。",
    transcript: "未使用ライセンスを削減したい。",
  },
  {
    id: "memo-snippets",
    category: "メモ",
    title: "断片メモ保管",
    summary: "会話中のキーワード断片をまとめて一時保存する。",
    createdAtLabel: "1時間前",
    pinned: false,
    summaryA: [
      { id: "mm1", text: "断片をタグ付きで保存" },
      { id: "mm2", text: "あとでカテゴリへ再配置" },
      { id: "mm3", text: "不要な断片は自動整理" },
    ],
    keyFacts: [{ id: "k1", icon: "pin", value: "未整理: 14件" }],
    openLoops: ["再配置の自動ルール"],
    recordingDuration: "00:28",
    tags: ["メモ", "記録", "断片"],
    expanded: "断片メモの一時保管。",
    transcript: "会話の断片をまとめておく。",
  },
  {
    id: "memo-reference-links",
    category: "メモ",
    title: "参照リンク置き場",
    summary: "調べもののURLとノート参照先をまとめる。",
    createdAtLabel: "2時間前",
    pinned: false,
    summaryA: [
      { id: "mr1", text: "資料リンクをカテゴリ単位で保存" },
      { id: "mr2", text: "重複URLの統合" },
      { id: "mr3", text: "有効期限の管理" },
    ],
    keyFacts: [{ id: "k1", icon: "reference", value: "参照先 27件" }],
    openLoops: ["リンク切れの検出"],
    recordingDuration: "00:34",
    tags: ["メモ", "記録", "リンク"],
    expanded: "参照情報の置き場。",
    transcript: "参考URLをあとから辿れるようにしたい。",
  },
];

export const mockMemoDetail: Memo = mockRecentMemos[0];

export const mockSky: Sky = {
  backgroundImage: "/images/constellation-bg.png",
  periods: ["all", "week", "today"],
  categories: [
    "すべて",
    "アイデア",
    "やること",
    "調べもの",
    "買い物・ごはん",
    "学び",
    "約束・連絡",
    "お金",
    "メモ",
  ],
  zones: [
    { id: "z-idea", category: "アイデア", count: 0, x: 16, y: 22, size: 30 },
    { id: "z-todo", category: "やること", count: 0, x: 38, y: 36, size: 28 },
    { id: "z-learn", category: "学び", count: 0, x: 61, y: 18, size: 27 },
    { id: "z-memo", category: "メモ", count: 0, x: 30, y: 61, size: 29 },
    { id: "z-money", category: "お金", count: 0, x: 74, y: 54, size: 15 },
    { id: "z-search", category: "調べもの", count: 0, x: 53, y: 52, size: 20 },
    { id: "z-shop", category: "買い物・ごはん", count: 0, x: 22, y: 46, size: 18 },
    { id: "z-promise", category: "約束・連絡", count: 0, x: 72, y: 34, size: 18 },
  ],
  stars: [],
  links: [],
};

export async function getRecentMemos(): Promise<Memo[]> {
  return mockRecentMemos;
}

export async function getMemoById(id: string): Promise<Memo | null> {
  const all = [...mockRecentMemos, ...mockInboxMemos];
  const memo = all.find((item) => item.id === id);
  return memo ?? null;
}

export async function getSky(): Promise<Sky> {
  return mockSky;
}
